version: '3.8'

services:
  app:
    build: .
    command: uvicorn wallets_api.main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/paymentProcessor
    networks:
      - backend      
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=paymentProcessor
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:

networks:
  backend: