version: '3.8'

services:
  app:
    build: .
    command: uvicorn wallet_api.main:app --host 0.0.0.0 --port 8080
    ports:
      -8080:8080
    networks:
      - backend
    volumes:
      - .:/app

networks:
  backend: