version: '3.8'

services:
  app:
    build: .
    command: uvicorn wallets_api.main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - .:/app

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=paymentProcessor
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: